spring:
  cloud:
    gateway:
      routes:
#        - id: AUTHENTICATION
#          uri: lb://AUTHENTICATION
#          predicates:
#            - Path=/api/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 100
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: COUNT_BASED
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    userCircuitBreaker:
      baseConfig: default

server:
  port: 8181