spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
#        - id: AUTHENTICATION
#          uri: lb://AUTHENTICATION
#          predicates:
#            - Path=/api/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 100
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: COUNT_BASED
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    userCircuitBreaker:
      baseConfig: default

server:
  port: 8181

#Actuator and circuit breaker
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true